### ISSUE TITLE
Some questions ...

### ISSUE THREAD

**Issue by dunky11** [mindslab-ai/nuwave2#1]
Hey, first of all, great results and solid paper. I have some questions:

1. Are you planning on releasing the weights?
2. For how many iterations did you train (I see it's ~1.4M in the graph but I just wanna be sure)?
3. How much time did it roughly take to train the model (I noticed you trained on a batch size of 24) and which GPU was used?

Thanks for any help in advance!

**Comment by dunky11** [comment]
If you don't plan on releasing the weights, I may be able to train this on a large-scale multilingual and proprietary dataset (3M samples,  8000 speakers) and release the weights, but it really depends on how much time it takes. If you plan on releasing the weights I will fine-tune it instead.

**Comment by Seungwoo0326** [comment]
Hi! Thank you for your interest.

First of all, the checkpoint will also be available soon.
We trained our model over 1.0M iterations with 2 NVIDIA A100 GPUs and it took more than 3 weeks.

We will release the pre-trained model as soon as possible so you can finetune it.
Hope you get a better result with finetuning!

**Comment by Seungwoo0326** [comment]
@dunky11 The pre-trained model is now available!
