### ISSUE TITLE
RuntimeError: CUDA out of memory.

### ISSUE THREAD

**Issue by Michaelwhite34** [mindslab-ai/nuwave2#4]

**Comment by Seungwoo0326** [comment]
Depending on your resources, you may have to reduce the batch size.
We trained on two NVIDIA A100 (40GB) GPUs.

**Comment by Michaelwhite34** [comment]
> Depending on your resources, you may have to reduce the batch size. We trained on two NVIDIA A100 (40GB) GPUs.

Hi, I can't find which file to change batch size, can you tell me the location ? (I mean testing.)

**Comment by Seungwoo0326** [comment]
Did you mean you got the error during testing? If so, the error would occur because the input audio was so long. 
If you got the error during training, you need to reduce the batch_size below.
https://github.com/mindslab-ai/nuwave2/blob/c05a0b6135ce1c46b9a5e57f132f18d3e3091745/hparameter.yaml#L2
