### ISSUE TITLE
Whether sampling.py in nuwave can be used in nuwave2

### ISSUE THREAD

**Issue by psp0001060** [mindslab-ai/nuwave2#7]
Thank you for your great contribution!
I see how to train and test but I don't see any examples of how to use it.  How do I upsample a wav once the model is trained?

I want to use the official checkpoint for audio upsampling. Can [sampling.py](https://github.com/mindslab-ai/nuwave/blob/f941928c12db6d0e325e8c1997079d274ea4cede/sampling.py) be used directly in nuwave2.

**Comment by Seungwoo0326** [comment]
Hi, you can check inference part in README.
You can use inference.py in nuwave2 for sampling.

**Comment by psp0001060** [comment]
thank you.
