### ISSUE TITLE
Setting to reduce memory usage during inference?

### ISSUE THREAD

**Issue by dillfrescott** [mindslab-ai/nuwave2#9]
I am using a device with over 30 GB of memory and its still topping out, hard. Is there a way to reduce this amount used during inference?

**Comment by junjun3518** [comment]
Hello @dillfrescott!

Thank you for your interest. I wanted to let you know that diffusion models, which need to be designed for high dimensionality input (which should be the same as the output), can consume a lot of memory. To prevent OOM errors, I recommend cutting the audio files.

Best regards,
Junhyeok Lee

**Comment by jreoka** [comment]
Okay thank you!
